### ISSUE TITLE
Error: Unable to recognize workspace format

### ISSUE THREAD

**Issue by suclike** [xamarinhq/test-cloud-espresso-extensions#2]
Executing the following command: 
`xtc test yourAppFile.apk 9da747640c21e8e227a5b58d098e42fb --devices 1f37af07 --series "master" --user user@email.com --workspace app/build/outputs/apk`

gives me the error  - "Error: Unable to recognize workspace format". I tried to wrap workspace path with "" or with '', none of these helped.

**Comment by sapieneptus** [comment]
Hey @suclike -

First off, please make sure you've got the most recent version of the uploader, as it has been updated. If the issue still persists, read on:

What is the content of `app/build/outputs/apk`? I.e., if you `ls` the directory, what's in there? Because the `xtc` tool supports multiple testing frameworks, we determine that it's an `espresso` framework by trying to find an apk with matching the name `"*-androidTest.apk"`.

Also, just making sure you are replacing `yourAppFile.apk`with the path to your actual application? 

Let me know if that resolves the problem; if not feel free to email me: chfuen<at>microsoft.com

**Comment by sapieneptus** [comment]
(Also, @suclike, I would recommend not putting your API key publicly on Github :)
